/**
 * Pure scaffold: copy template → inject config header → replace {{TOKENS}} → forbid leftover `{{`.
 * No validators / site-builder / themes. Next: `pnpm site validate` then `pnpm site build`, or `pnpm site pipeline`.
 */
import type { Dirent } from "node:fs";
import { access, cp, readFile, readdir, rename, writeFile } from "node:fs/promises";
import { dirname, extname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { requireSiteCliInvocation } from "../../scripts/site-script-guard.js";

const SLUG_PATTERN = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");
const TEMPLATE_ROOT = join(REPO_ROOT, "templates", "demo-technical-product-showcase");

const SOURCE_CONFIG_FILENAME = "site.config.template.ts";
const TARGET_CONFIG_FILENAME = "site.config.ts";

const SITE_CONFIG_HEADER = `import { defineSiteConfig } from "@factory/validators";\n\n`;

async function main(): Promise<void> {
  requireSiteCliInvocation("create-site");

  const siteSlug = process.argv[2];
  if (!siteSlug || !SLUG_PATTERN.test(siteSlug)) {
    console.error("Usage: pnpm site create <kebab-site-slug>");
    process.exit(1);
    return;
  }

  const siteDir = join(REPO_ROOT, "sites", siteSlug);

  try {
    await access(siteDir);
    console.error(`Refusing to overwrite existing site directory: ${siteDir}`);
    process.exit(1);
    return;
  } catch {
    /* absent — OK */
  }

  try {
    await access(join(TEMPLATE_ROOT, SOURCE_CONFIG_FILENAME));
    await access(join(TEMPLATE_ROOT, "content", "en", "pages", "index.json"));
    await access(join(TEMPLATE_ROOT, "content", "zh", "pages", "index.json"));
  } catch {
    console.error(`Missing template bundle under ${TEMPLATE_ROOT}`);
    process.exit(1);
    return;
  }

  /** ① template → copy */
  await cp(TEMPLATE_ROOT, siteDir, { recursive: true });

  /** ② rename + header */
  await rename(join(siteDir, SOURCE_CONFIG_FILENAME), join(siteDir, TARGET_CONFIG_FILENAME));
  let cfg = await readFile(join(siteDir, TARGET_CONFIG_FILENAME), "utf8");
  if (!cfg.startsWith("import { defineSiteConfig }")) {
    cfg = `${SITE_CONFIG_HEADER}${cfg}`;
    await writeFile(join(siteDir, TARGET_CONFIG_FILENAME), cfg, "utf8");
  }

  const displayTitle = siteSlug
    .split("-")
    .map((segment) => segment.charAt(0).toUpperCase() + segment.slice(1))
    .join(" ");
  const primaryHost = `${siteSlug}.example.com`;
  const TOK_EXTS = new Set([".ts", ".json"]);
  const table: Record<string, string> = {
    SITE_SLUG: siteSlug,
    DEPLOY_PROJECT_NAME: siteSlug,
    DISPLAY_NAME_EN: displayTitle,
    DISPLAY_NAME_ZH: "占位：请修改为中文公司名称",
    DOMAIN: `https://${primaryHost}`,
    PRIMARY_HOST: primaryHost,
    LEGAL_NAME: `${displayTitle} Co., Ltd.`,
    REGISTERED_COUNTRY: "United States",
    REGISTERED_ADDRESS:
      "100 Main Street, Suite 100, Wilmington, DE 19801, United States (CHANGE_ME)",
    INDUSTRY: "Industrial B2B (site factory template)",
    DEFAULT_DESCRIPTION_EN: `${displayTitle} — scaffolded site generated by Site Factory. Replace copy, legal text, contacts, and domain before launch.`,
    DEFAULT_DESCRIPTION_ZH: `${displayTitle} 站点由 Site Factory 模板自动生成，请在上线前替换文案、法务信息、联系方式与域名。`,
  };

  /** ③ replace + ④ validate residues */
  let stack = [siteDir];
  while (stack.length > 0) {
    const current = stack.pop() as string;
    const entries: Dirent[] = await readdir(current, { withFileTypes: true });
    const childDirs = entries.filter((e) => e.isDirectory()).map((e) => join(current, e.name));
    stack = stack.concat(childDirs);

    for (const e of entries) {
      if (!e.isFile() || !TOK_EXTS.has(extname(e.name).toLowerCase())) continue;
      const filePath = join(current, e.name);
      let text = await readFile(filePath, "utf8");
      for (const [k, value] of Object.entries(table)) {
        text = text.split(`{{${k}}}`).join(value);
      }
      if (text.includes("{{")) {
        throw new Error(`Unresolved "{{" placeholders remain in ${filePath}`);
      }
      await writeFile(filePath, text, "utf8");
    }
  }

  console.log(`create-site OK → ${siteDir}`);
}

main().catch((reason: unknown) => {
  const message = reason instanceof Error ? reason.message : String(reason);
  console.error(`create-site failed: ${message}`);
  process.exit(1);
});
